// <auto-generated />
using System;
using Backend.Src.Infrastructure.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919053634_AddCvProcessingStatus")]
    partial class AddCvProcessingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Src.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("CreditBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMERIC")
                        .HasDefaultValue(3m);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Curriculums.Cv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("FileContentKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Ready");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CandidateId", "IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\" = true");

                    b.ToTable("Cvs", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosesAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("UUID");

                    b.Property<string>("CompensationType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalCompanyImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalCompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("NUMERIC");

                    b.Property<decimal?>("MinSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("OpensAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("OriginPage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubigeo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkHours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.News.Post", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("UUID");
                    b.Property<string>("Content").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMPTZ");
                    b.Property<Guid?>("JobId").HasColumnType("UUID");
                    b.Property<int>("LikeCount").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);
                    b.Property<string>("PostType").IsRequired().HasColumnType("TEXT");
                    b.Property<Guid>("ProfileId").HasColumnType("UUID");
                    b.Property<string>("Title").IsRequired().HasColumnType("text");
                    b.Property<int>("Views").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);
                    b.HasKey("Id");
                    b.HasIndex("JobId");
                    b.HasIndex("ProfileId");
                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.News.PostImage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("Order").HasColumnType("integer");
                    b.Property<Guid>("PostId").HasColumnType("UUID");
                    b.Property<string>("Url").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("PostId");
                    b.ToTable("PostImage");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Payments.Payment", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("CreditPlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Payments_UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.CandidateProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Dni")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProfileId");

                    b.ToTable("CandidateProfiles", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.CompanyProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("UUID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanySize")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Ruc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("UUID");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("CompanyProfiles", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UUID");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("UUID");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.LanguageKnown", b =>
                {
                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("UUID");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("LanguageLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("CandidateProfileId", "LanguageCode", "LanguageLevel");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubigeo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UUID");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("UUID");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("WorkExperiences", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Recommendation.JobInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("JobId");

                    b.HasIndex("CandidateProfileId", "JobId");

                    b.ToTable("JobInteractions", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Recruitment.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("UUID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("CvStorageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("UUID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CandidateId")
                        .IsUnique();

                    b.ToTable("JobApplications", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.Property<Guid>("JobsId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("UUID");

                    b.HasKey("JobsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("JobSkills", (string)null);
                });

            modelBuilder.Entity("ProfileSkill", b =>
                {
                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("UUID");

                    b.HasKey("ProfilesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ProfileSkills", (string)null);
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Curriculums.Cv", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Jobs.Job", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.CompanyProfile", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.News.Post", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Jobs.Job", "Job")
                        .WithMany().HasForeignKey("JobId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.Profile", null)
                        .WithMany().HasForeignKey("ProfileId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.News.PostImage", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.News.Post", null)
                        .WithMany("PostImages").HasForeignKey("PostId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Payments.Payment", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.News.Post", b =>
                {
                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.CandidateProfile", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.Profile", "Profile")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("Backend.Src.Domain.Entities.Profiles.CandidateProfile", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.CompanyProfile", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.Profile", "Profile")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("Backend.Src.Domain.Entities.Profiles.CompanyProfile", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Src.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.Education", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.CandidateProfile", null)
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.LanguageKnown", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.CandidateProfile", null)
                        .WithMany("Languages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.Profile", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.WorkExperience", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.CandidateProfile", null)
                        .WithMany("WorkExperiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Recruitment.JobApplication", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Src.Domain.Entities.Skills.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileSkill", b =>
                {
                    b.HasOne("Backend.Src.Domain.Entities.Profiles.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Src.Domain.Entities.Skills.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.CandidateProfile", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Languages");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("Backend.Src.Domain.Entities.Profiles.Profile", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("CompanyProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
